name: test askomdch

on:
  push:
    branches:
      - main

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: run test
        run: mvn test
